import { Box, Button, Container, Stack, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import LeftContent from "../components/LeftContent";
import Navbar from "../components/Navbar";
import RightContent from "../components/RightContent";
import TopBanner from "../components/TopBanner";
import DetailPage from "./DetailPage";

export default function Home() {
  return (
    <Box sx={{ backgroundColor: "#F5F5F5" }}>
      <Head>
        <title>Open Rent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <DetailPage />
      <Footer />
    </Box>
  );
}
