import { Box, Button, Container, Stack } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import LeftContent from "../components/LeftContent";
import Navbar from "../components/Navbar";
import RightContent from "../components/RightContent";
import TopBanner from "../components/TopBanner";

export default function Home() {
  return (
    <Box sx={{ backgroundColor: "#F5F5F5" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container>
        <TopBanner />
        <Stack direction={{ xs: "column", sm: "row" }}>
          <LeftContent />
          <RightContent />
        </Stack>
      </Container>
    </Box>
  );
}
