import { Button, Container, Stack } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import LeftContent from "../components/LeftContent";
import Navbar from "../components/Navbar";
import RightContent from "../components/RightContent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container>
        <Stack>
          <LeftContent />
          <RightContent />
        </Stack>
      </Container>
    </>
  );
}
